FROM python:3.10-slim

WORKDIR /app

# Copy everything
COPY . .

# Install dependencies
RUN pip install -r requirements.txt
RUN pip install --no-cache-dir -e ./shared

EXPOSE 8080

CMD ["python", "api_server_caller.py"]