version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --eval \"db.adminCommand('ping')\" > /dev/null 2>&1"]
      interval: 5s
      timeout: 30s
      retries: 5
    env_file:
      - .env
    command: >
      mongod --quiet --setParameter logComponentVerbosity="{\"network\":{\"verbosity\":-1}}"

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  scraper:
    build:
      context: .
      dockerfile: Dockerfile.scraper
    env_file:
      - .env
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      - MONGO_URI=mongodb://mongodb:27017

volumes:
  mongodb_data: